:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement: preamble
:sectlinks:
:sectanchors:
:sectnums:
:d2: /opt/homebrew/bin/d2

== Architecture

The Chrome and Electron versions of the app share the exact same UI code, but in both systems the UI code must
communicate with a separate background system.
We use fulcro-devtools-remote to abstract this away.

[d2]
-----
Fulcro App <-> Fulcro Devtool Remote
Fulcro Devtool Remote <-> Dev Tools UI: serialized
-----

See Fulcro Devtool Remote for more details.

== Building

Building MacOS Electron releases is done as follows:

----
$ pnpm install
$ cd shells/electron
$ vi package.json     # Update version number
$ pnpm install
$ pnpm rebuild electron
$ pnpm run install-app-deps
$ cd ../..
$ pnpm exec shadow-cljs release electron-main electron-renderer
$ cd shells/electron
$ pnpm exec electron-builder build -m
----

pnpm is configured (in `pnpm-workspace.yaml`) to never run dependency install scripts, so after installing in
`shells/electron` you must deliberately fetch the Electron binary with `pnpm rebuild electron`. electron-builder's
`install-app-deps` is no longer a `postinstall` hook either; run `pnpm run install-app-deps` there yourself when native
dependencies need rebuilding for Electron.

See the `Makefile` for other builds

== Chrome

First, make sure to update the version number in `shells/chrome/manifest.edn`.

Then build the zip file that can be uploaded to the Chrome store:

----
pnpm install
script/release-chrome
----

The result will be in a zip file in `releases`.
